sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Gy202324111213
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    bucket-name: java-sky-take-out-pj
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx13bfeba280fedc3f
    secret: 5702137bb7f04c1b823230779d179985
    # 微信支付参数配置
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://9ea0754.r19.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://9ea0754.r19.cpolar.top/notify/refundSuccess
  shop:
    address: 广东省肇庆市端州区星湖国际广场4楼
  baidu:
    ak: VGrEqzeRWEiq0tyhRHd6jN7UZ8ABhKf2
  #  对rabbitmq进行参数配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
